"""
NODE 4 — Digital Signature Check (Legit ba ang nagpadala?)
Port: 5004
Verifies the RSA digital signature of the request using the sender's public key.
"""

import socket
import json
import base64
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding
from cryptography.exceptions import InvalidSignature

HOST = '127.0.0.1'
PORT = 5004

# Load public key from file (generated by Security Designer)
# In production: load from keys.json or .pem file
PUBLIC_KEY_PATH = "public_key.pem"


def load_public_key():
    """Load RSA public key from .pem file."""
    try:
        with open(PUBLIC_KEY_PATH, "rb") as f:
            return serialization.load_pem_public_key(f.read())
    except FileNotFoundError:
        print(f"[NODE 4] WARNING: {PUBLIC_KEY_PATH} not found. Generate keys first.")
        return None


def verify_signature(message: str, signature_b64: str) -> str:
    """Verify RSA signature against the message."""
    public_key = load_public_key()
    if public_key is None:
        return "FAIL"

    try:
        signature = base64.b64decode(signature_b64)
        public_key.verify(
            signature,
            message.encode(),
            padding.PKCS1v15(),
            hashes.SHA256()
        )
        return "PASS"
    except InvalidSignature:
        return "FAIL"
    except Exception as e:
        print(f"[NODE 4] Error: {e}")
        return "FAIL"


def start_node():
    print(f"[NODE 4] Digital Signature Check — Listening on port {PORT}...")
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        s.bind((HOST, PORT))
        s.listen()

        while True:
            conn, addr = s.accept()
            with conn:
                data = conn.recv(4096).decode()
                if not data:
                    continue

                try:
                    payload = json.loads(data)
                    message = payload.get("message", "")
                    signature = payload.get("signature", "")
                    result = verify_signature(message, signature)
                except Exception as e:
                    result = "FAIL"
                    print(f"[NODE 4] Error: {e}")

                print(f"[NODE 4] Result: {result}")
                conn.sendall(result.encode())


if __name__ == "__main__":
    start_node()
